<h3 class="font-monospace mt-3">My rank</h3>
<!-- write content between this div -->
<div class="border rounded-3 my-4">
    <div class="mx-md-5">
        <table class="table table-responsive my-4">
            <thead>
                <th>#NO</th>
                <th>User</th>
                <th>Cuntry</th>
                <th>Score</th>
                <th>Date</th>
            </thead>
            <tbody>
                <tr>
                    <td>1</td>
                    <td>Amir</td>
                    <td>Afghanistan</td>
                    <td>400</td>
                    <td>2040-10-11</td>
                </tr>
                <tr>
                    <td>1</td>
                    <td>Amir</td>
                    <td>Afghanistan</td>
                    <td>400</td>
                    <td>2040-10-11</td>
                </tr>
                <tr>
                    <td>1</td>
                    <td>Amir</td>
                    <td>Afghanistan</td>
                    <td>400</td>
                    <td>2040-10-11</td>
                </tr>
                <tr>
                    <td>1</td>
                    <td>Amir</td>
                    <td>Afghanistan</td>
                    <td>400</td>
                    <td>2040-10-11</td>
                </tr>
                <tr>
                    <td>1</td>
                    <td>Amir</td>
                    <td>Afghanistan</td>
                    <td>400</td>
                    <td>2040-10-11</td>
                </tr>
                <tr>
                    <td>1</td>
                    <td>Amir</td>
                    <td>Afghanistan</td>
                    <td>400</td>
                    <td>2040-10-11</td>
                </tr>
                <tr>
                    <td>1</td>
                    <td>Amir</td>
                    <td>Afghanistan</td>
                    <td>400</td>
                    <td>2040-10-11</td>
                </tr>
                <tr>
                    <td>1</td>
                    <td>Amir</td>
                    <td>Afghanistan</td>
                    <td>400</td>
                    <td>2040-10-11</td>
                </tr>
                <tr>
                    <td>1</td>
                    <td>Amir</td>
                    <td>Afghanistan</td>
                    <td>400</td>
                    <td>2040-10-11</td>
                </tr>
                <tr>
                    <td>1</td>
                    <td>Amir</td>
                    <td>Afghanistan</td>
                    <td>400</td>
                    <td>2040-10-11</td>
                </tr>
                <tr>
                    <td>1</td>
                    <td>Amir</td>
                    <td>Afghanistan</td>
                    <td>400</td>
                    <td>2040-10-11</td>
                </tr>
                <tr>
                    <td>1</td>
                    <td>Amir</td>
                    <td>Afghanistan</td>
                    <td>400</td>
                    <td>2040-10-11</td>
                </tr>
                <tr class="bg-success text-light">
                    <td>YOU > 99</td>
                    <td>Amir</td>
                    <td>Afghanistan</td>
                    <td>400</td>
                    <td>2040-10-11</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>